apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-backend
  labels:
    app: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php-backend
        image: kaivalyabachkar/three-tier-architecture-php:latest
        ports:
        - containerPort: 9000 
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef: 
              name: mysql-credentials 
              key: DB_NAME